# Generated by Django 5.2 on 2025-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackCounter',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
