# Generated by Django 5.2 on 2025-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0002_attackcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackcounter',
            name='last_emailed',
            field=models.IntegerField(default=0),
        ),
    ]
